### ISSUE TITLE
when will the code be released? thx~

### ISSUE THREAD

**Issue by changhy666** [imankgoyal/NonDeepNetworks#2]

**Comment by huyiming2016** [comment]
I have the same question

**Comment by zhangzien123456** [comment]
me too

**Comment by imankgoyal** [comment]
Unfortunately, we have some delay in releasing the code. We sincerely regret the inconvenience. We have the updated the readme.

**Comment by imankgoyal** [comment]
Thank you so much for the patience. The preliminary version for the imagenet dataset is available in the imagenet folder.
