### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by SenShu96** [imankgoyal/NonDeepNetworks#4]
I am very interested in your work and would like to further study. I hope you can release the code as soon as possible in your busy schedule. Thank you！

**Comment by kadirbeytorun** [comment]
Hey @imankgoyal, will you also release config files for ParNet-XL-CSP and other detection configs for ParNet?

**Comment by imankgoyal** [comment]
Thank you so much for the patience. The preliminary version for the imagenet dataset is available in the imagenet folder.
