### ISSUE TITLE
Question about SSE module

### ISSUE THREAD

**Issue by Tsianmy** [imankgoyal/NonDeepNetworks#6]
Hi. Figure 2b shows that there's one 1x1conv in a branch of SSE, how to match the channel of output by 1x1conv with the channel of input after shortcut? If I set the output channel of 1x1conv the same as input, the channels of the outputs by RepVGG block and SSE will not match.

**Comment by imankgoyal** [comment]
Hello,

Thanks for your interest in our work. The ParNet block in figure 2b has the same number of channels in input and output. For dowsampling and fusion, the block diagrams are in the appendix.

Thanks!

**Comment by Tsianmy** [comment]
I see. Thanks for your response.
