### ISSUE TITLE
When will the code be released? Thanks.

### ISSUE THREAD

**Issue by sunhui-3D** [imankgoyal/NonDeepNetworks#7]

**Comment by imankgoyal** [comment]
Unfortunately, we have some delay in releasing the code. We sincerely regret the inconvenience. We have the updated the readme.

**Comment by jimmyflycv** [comment]
2 months...already

**Comment by imankgoyal** [comment]
Thank you so much for the patience. The preliminary version for the imagenet dataset is available in the imagenet folder.
