### ISSUE TITLE
when will the code of the model be released?

### ISSUE THREAD

**Issue by Dr-Goopher** [imankgoyal/NonDeepNetworks#8]
I am very interested in your research, when will the code of the model be released? I saw on October 23rd that you said it would be released in 4 weeks

**Comment by imankgoyal** [comment]
Hello, thanks for your interest in our work. We plan to release a version by the end of the week.

**Comment by Dr-Goopher** [comment]
Ok, thanks for your reply

**Comment by imankgoyal** [comment]
Unfortunately, we have some delay in releasing the code. We sincerely regret the inconvenience. We have the updated the readme.

**Comment by MorvanLi** [comment]
It's a bad news, I've been waitting the code for a long time.

**Comment by RahulBhalley** [comment]
I just hope this work doesn't end up like TimbreTron https://github.com/huangsicong/TimbreTron/issues/1. This seems like really good work. What I've seen is as time passes better techniques get explored and the current ones become obsolete, hence, researchers' effort go in vain.

**Comment by imankgoyal** [comment]
Thank you so much for the patience. The preliminary version for the imagenet dataset is available in the imagenet folder.
