### ISSUE TITLE
Problem about replacing the backbone of YOLOv4 with ParNet.

### ISSUE THREAD

**Issue by Gumpest** [imankgoyal/NonDeepNetworks#9]
Which three layers' outputs for neck fusion when the three stream is parallel.
Those three ones?
Thanks a lot！
![1638517933(1)](https://user-images.githubusercontent.com/56063339/144565620-d46a74fd-38db-4458-9c79-0153d259c923.png)

**Comment by imankgoyal** [comment]
If I understand the question correctly, yes the marked layers are the output of each stream. The output of stream 1 (largest resolution) is passed to down sampling. The output of stream 2 and stream 3 are passed to fusion blocks.
